groot-build:
	docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag jkaflik/behaviortree-groot:latest -f groot.Dockerfile .

groot-publish:
	docker push jkaflik/behaviortree-groot:latest
